### ISSUE TITLE
O11y testing abstraction is broken

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-kubeflow-chisme#104]
### Bug Description

The charm grafana-agent-k8s was moved back to revision 45 in stable channel. (e.g. [this](https://github.com/canonical/argo-operators/actions/runs/9610825972/job/26508108957#step:4:501) action shown that rev 68 was used before) This cause an issue, since status message is different from it was expected.

After some discussion in team, we think the abstraction she should not obey the workload status message after grafana-agent-k8s is deployed.  It means that these [lines](https://github.com/canonical/charmed-kubeflow-chisme/blob/a429474f0d81dd76aaa13d8f340230eafd78c16b/src/charmed_kubeflow_chisme/testing/cos_integration.py#L110-L116) should be removed.

Currently, the workaround is to deploy grafana-agent-k8s from latest/edge channel , e.g. `deploy_and_assert_grafana_agent(..., channel="latest/edge", ...)`

### To Reproduce

tox -e integration

### Environment

Juju 3.4+
Microk8s 1.24+

### Relevant Log Output

```shell
File "/home/runner/work/kfp-operators/kfp-operators/.tox/integration/lib/python3.8/site-packages/charmed_kubeflow_chisme/testing/cos_integration.py", line 116, in deploy_and_assert_grafana_agent
    assert GRAFANA_AGENT_MESSAGE.match(msg), error_msg
AssertionError: grafana-agent-k8s did not reach expected state. 'grafana-cloud-config: off, logging-consumer: off' != 'Missing (?=.*\['grafana-cloud-config'\]|\['grafana-dashboards-provider'\] for grafana-dashboards-consumer)(?=.*\['grafana-cloud-config'\]|\['logging-consumer'\] for logging-provider)(?=.*\['grafana-cloud-config'\]|\['send-remote-write'\] for metrics-endpoint)'
```

**Comment by DnPlas** [comment]
Re-opening as we still need to bump chisme versions in repos where this code is used.

**Comment by DnPlas** [comment]
Chisme 0.4.1 is out, and is now updated in all repos. We can close this task.
