### ISSUE TITLE
Expose optional `force` parameter in `apply()` in kubernetes resource handler

### ISSUE THREAD

**Issue by i-chvets** [canonical/charmed-kubeflow-chisme#35]
# Description
Expose optional `force` parameter in `apply()` in kubernetes resource handler.

In some cases `force` parameter is required in order to apply resources in the cluster.

**Comment by DnPlas** [comment]
Thanks @i-chvets,  this sounds interesting. Have you explored the `--force-conflicts` option? It seems a little bit less aggressive than `--force`. Looking at the [docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply):

* force: "If true, immediately remove resources from API and bypass graceful deletion. "
* force-conflicts: "If true, server-side apply will force the changes against conflicts. "

It sounds to me like`force` may cause issues if the resource gets deleted suddenly to be then re-applied, whereas `force-conflicts` will try to just force the changes against conflicts. Either option must be used carefully, though, I think we should only use `force*` iff the conflict is something we are sure won't represent any trouble with existing `CRs`.

**Comment by i-chvets** [comment]
Answer in 4 parts:
1. In server-side apply functionality `--force-conflicts` only exist in K8S API, not in `lightkube`. [This is the API](https://github.com/gtsystem/lightkube/blob/7f4eb8110476fd0c13045de618010a6081c049ec/lightkube/core/client.py#L439) we are using.
2. Looks like `force=True` in `lightkube` API is the same as using `--force-conflicts` in K8S API.
3. Interesting point about doing `force=True` on upgrade only (discussed below).
4. This issue requests change in API to expose `force` parameter. Its usage can be discussed in appropriate issues where we are trying to solve conflicts during upgrade.

Forcing conflicts during upgrade only (really should be discussed in the charm specific issues):
Can customer change those CRDs? They are owned by the charm and should not be touched, right?
What if customer did some changes to those CRDs? All other events (config-change, add-relation, etc.) will fail on K8S resource apply if `force` is not used. Upgrade will be the only one that will succeed and will overwrite customer changes.
